### ISSUE TITLE
Expand processing_pool configuration to handle multiple worker types

### ISSUE THREAD

**Issue by markstory** [getsentry/taskbroker#313]
The current `processing_pool` configuration set only accommodates `getsentry` workers, but we'll also need `getsentry-control` workers for control silo in saas.

Expanding the `processing_pools.worker` attributes to include a worker profile/name would let us generate workers in different services.

```yaml
processing_pools:
- name: control
  description: "control pool"
  kafka_topic: "taskbroker-control"
  kafka_cluster: "kafka-001:9092"
  kafka_consumer_group: "taskbroker-control"
  app_feature: "control"
 broker:
    replicas: 1
    cpu: "8"
    memory: "16Gi"
    max_pending_count: 2048
    worker_threads: 16
    sqlite_storage: 100Mi
  worker:
    # Workers are generated by this service (defaults to getsentry)
    worker_service: getsentry-control

    # The number of child workers to spawn in each worker.
    concurrency: 32
```

We'll need a scheduler and worker in control silo, as control has different scheduled tasks.
